name: Build release with Webpack

on: 
  push:
    paths:
      - 'src/**'
      - 'gallery/**'
      - 'webpack.config.js'
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Package Metadata"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Clear Dist Folder
      run: rm -rf ./dist/gallery/packages/

    - name: Build
      run: npm run build

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Build Dist" || exit 0
        git push