name: Generate and Deploy

on: 
  push:
    paths:
      - 'gallery/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Manifest
        run: node ./utils/create-readme-metadata.js

      - name: Update documentation with package metadata
        run: node ./utils/create-docs.js

      - name: Generate Metadata
        run: node ./utils/create-metadata.js

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Webpack build from GitHub Actions" || exit 0
          git push