name: Generate and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Manifest
        run: node create-readme-metadata.js

      - name: Commit and Push
        run: |
          git checkout -b generated-branch-$(date +'%Y%m%d%H%M%S')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated gallery.manifest file" || echo "No changes to commit"
          git push origin HEAD

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/github-script@v5
        with:
          script: |
            github.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'